In [ ]:
import numpy as np

## solveGaussJordanPivotagemTotal

In [5]:
def solveGaussJordanPivotagemTotal(A, b):
    M = len(b)
    linhas = np.arange(M)
    colunas = np.arange(M + 1)
    AA = np.zeros([M, M+1])
    AA[:M,:M] = A
    AA[:,M] = b
    aa = np.zeros(M * M)

    for p in range(M):
        m = M - p
        for i in range(m):
            aa[i * m:(i + 1) * m] = AA[linhas[p + i], colunas[p:-1]]
        print(aa[:m * m])
        index = np.argmax(np.abs(aa[:m * m]))

        l1 = p + index // m
        c1 = p + index % m
        linhas[p], linhas[l1] = linhas[l1], linhas[p] 
        colunas[p], colunas[c1] = colunas[c1], colunas[p]        
        AA[linhas[p], colunas[:] ] /= AA[linhas[p],colunas[p]]
        for i in range(p):
            AA[linhas[i],colunas[p:]] -= AA[linhas[p],colunas[p:]] * AA[linhas[i],colunas[p]]
            
        for i in range(p + 1, M):
            AA[linhas[i],colunas[p:]] -= AA[linhas[p],colunas[p:]] * AA[linhas[i],colunas[p]]

    return AA[colunas[linhas[:]], -1]

AA = np.array([[0.1,1,2, 4.1],[3,4.1,5,2],[6,7,8,5],[0.5,0,3,5]])
BB = np.array([0.1, 0.2, 0.3, 0.4])
sol = solveGaussJordanPivotagemTotal(AA.copy(), BB.copy())
np.dot(AA, sol) - BB


[0.1 1.  2.  4.1 3.  4.1 5.  2.  6.  7.  8.  5.  0.5 0.  3.  5. ]
[-0.275 -0.75  -1.125 -0.75  -1.4    2.85  -2.625 -1.75   3.125]
[ 0.196  1.644 -1.38  -1.22 ]
[-1.23454988]


array([ 0.00000000e+00, -5.55111512e-17, -1.66533454e-16,  0.00000000e+00])

## LUDecompositionGaussPivot

In [6]:
def LUDecompositionGaussPivot(A):
    """
    Escrever explicitamente as expressões
    """
    M = len(A)
    L = np.zeros([M,M],dtype=float)
    U = np.copy(A)
    index = np.arange(M)
    
    for i in range(M):
        imax = i + np.argmax(np.abs(U[index[i:], i]))
        index[i], index[imax] = index[imax], index[i]
        
        L[index[i:],i] = U[index[i:], i]

        U[index[i],:] /= U[index[i],i]
        for k in range(i + 1, M):
            U[index[k],i:] -= U[index[k],i] * U[index[i],i:]

    print("Matriz L:\n", L,'\n')
    print("Matriz L reordenada:\n", L[index,:],'\n')
    print("Matriz U:\n", U[index,:],'\n')
    print(np.linalg.norm(A[index,:] - np.dot(L[index,:],U[index,:])), '\n')

## LUDecompositionPivot

In [4]:
def LUDecompositionPivot(A):
    """Pivotagem numa decomposição LU com expressões explicitas """
    M = len(A)
    L = np.zeros([M,M],dtype=float)
    U = np.identity(M)

    index = np.arange(M)
    
    for i in range(M):
        for k in range(i,M):
            L[index[k],i] = A[index[k],i] - np.dot(L[index[k],:i], U[:i,i])
            
        imax = i + np.argmax(np.abs(L[index[i:],i]))
        index[i], index[imax] = index[imax], index[i]
        
        for k in range(i,M):
            L[index[k],i] = A[index[k],i] - np.dot(L[index[k],:i], U[:i,i])
            
        for k in range(i + 1,M):
            U[i, k] = (A[index[i], k] - np.dot(L[index[i],:i], U[:i, k]) )/L[index[i],i]       
    print("Matriz L:\n", L,'\n')
    print("Matriz U:\n", U,'\n')
    print("Matriz L* U - A:\n", L @ U - A,'\n')
    print("___________________________________________________________________")
    print("Matriz L reordenada:\n", L[index,:],'\n')
    print("Matriz U:\n", U,'\n')
    print(np.linalg.norm(A[index,:] - np.dot(L[index,:],U)), '\n')
    

AA = np.random.random_sample([6,6])
LUDecompositionPivot(AA.copy())

print( LUDecompositionPivot(AA) )


Matriz L:
 [[ 0.74462987 -0.07334811  0.34224623 -0.83136252  0.          0.        ]
 [ 0.8534734   0.          0.          0.          0.          0.        ]
 [ 0.38595099  0.29553126 -0.00651349  0.54220147  0.55080703  0.        ]
 [ 0.45590925 -0.28472313  0.35869661  0.          0.          0.        ]
 [ 0.8164916  -0.35029618  0.          0.          0.          0.        ]
 [ 0.21994471 -0.11976193  0.03127853  0.60011468  0.01612772  0.44325329]] 

Matriz U:
 [[ 1.          0.9274842   0.61438212  0.41629773  0.77185424  0.6619381 ]
 [ 0.          1.         -0.49216143  0.2773534  -0.63059731 -0.09149371]
 [ 0.          0.          1.          1.60035939 -0.2626673   0.08789939]
 [ 0.          0.          0.          1.          0.27243083 -0.31228977]
 [ 0.          0.          0.          0.          1.          1.55142252]
 [ 0.          0.          0.          0.          0.          1.        ]] 

Matriz L* U - A:
 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.0