In [55]:
import numpy as np
from scipy.linalg import solve_banded
import math

N = 10
V_pos = 5  #Volts

v = np.zeros((N))
v[0] = v[1] = V_pos

A = np.zeros((N,N))
for i in range(2,N-2): #vai da linha 3 até à linha N-2
    A[i,i-2] = A[i,i-1] = A[i,i+1] = A[i,i+2] = -1
    A[i,i] = 4
    
#ajustar valores das 2 primeiras e 2 últimas linhas
A[0,1]=A[0,2]  =  A[1,0]=A[1,2]=A[1,3]  =  A[N-2,N-4]=A[N-2,N-3]=A[N-2,N-1]  =  A[N-1,N-3]=A[N-1,N-2] = -1
A[0,0] = A[N-1,N-1] = 3
A[1,1] = A[N-2,N-2] = 4

print(A)
print(v)
print("---")


#passar para matriz banda
linhas = 5
linhaCentro =  math.floor(linhas/2)
A2 = -np.ones((linhas,N))
A2[0,0:2] = A2[1,0] = A2[linhas-1,N-2:N] = A2[linhas-2,N-1] = 0
A2[linhaCentro,0] = A2[linhaCentro,N-1] = 3
for a in range(1,N-1):
    A2[linhaCentro,a] = 4
    
print(A2)


# #transforma uma   matriz de banda   numa   matriz de banda diagonal
# def transforma_banda(M): 
#     N = len(M[0,:]) #so funciona para matrizes quadradas
    
#     #Contar quantas diagonais e subdiagonais tem a matriz
#     cont = -1  # é -1 pois o código conta a diagonal duas vezes
#     for i in range(N):
#         if M[0,i] != 0 and M[i,0] != 0:
#             cont+=2
#         elif M[i,0] != 0 :
#             cont+=1
#         elif M[0,i] != 0 :
#             cont+=1
#     print(cont)
    
#     T = np.zeros((cont,N))
#     for i in range(N):
#         l_central = math.floor(cont/2)
#         T[l_central-2,i] = M[i,i-2]
#         T[l_central-1,i] = M[i,i-1]
#         T[l_central,i] = M[i,i]
#         print(i+1)
#         if i+2>=N : 
#             T[l_central+1,i] = 0
#             T[l_central+2,i] = 0
#         else:
#             T[l_central+1,i] = M[i+1,i]
#             T[l_central+2,i] = M[i+2,i]
        
#     return T

# transforma_banda(A)

sol = solve_banded((2,2),A2,v)
print(sol)


[[ 3. -1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.  0.  0.  0.  0.]
 [-1. -1.  4. -1. -1.  0.  0.  0.  0.  0.]
 [ 0. -1. -1.  4. -1. -1.  0.  0.  0.  0.]
 [ 0.  0. -1. -1.  4. -1. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. -1.  4. -1. -1.  0.  0.]
 [ 0.  0.  0.  0. -1. -1.  4. -1. -1.  0.]
 [ 0.  0.  0.  0.  0. -1. -1.  4. -1. -1.]
 [ 0.  0.  0.  0.  0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1. -1.  3.]]
[5. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
---
[[ 0.  0. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 3.  4.  4.  4.  4.  4.  4.  4.  4.  3.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  0.  0.]]
[4.12573674 3.9194499  3.45776031 3.09430255 2.69155206 2.30844794
 1.90569745 1.54223969 1.0805501  0.87426326]
