In [10]:
import numpy as np 
from scipy.linalg import lu

A = np.array([[ 4,-1,-1,-1],
              [-1, 3, 0,-1],
              [-1, 0, 3,-1],
              [-1,-1,-1, 4]],float)

P,L,U = lu(A)

print(A, "= A")
print("---")
print(P, "= P")
print("---")
print(L, "= L")
print("---")
print(U, "= U")

[[ 4. -1. -1. -1.]
 [-1.  3.  0. -1.]
 [-1.  0.  3. -1.]
 [-1. -1. -1.  4.]] = A
---
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] = P
---
[[ 1.          0.          0.          0.        ]
 [-0.25        1.          0.          0.        ]
 [-0.25       -0.09090909  1.          0.        ]
 [-0.25       -0.45454545 -0.5         1.        ]] = L
---
[[ 4.         -1.         -1.         -1.        ]
 [ 0.          2.75       -0.25       -1.25      ]
 [ 0.          0.          2.72727273 -1.36363636]
 [ 0.          0.          0.          2.5       ]] = U


In [11]:
print(L@U)

[[ 4. -1. -1. -1.]
 [-1.  3.  0. -1.]
 [-1.  0.  3. -1.]
 [-1. -1. -1.  4.]]


In [3]:
#Não tou aa conseguir fazer o L

import numpy as np 

def ElimG_LU(A,v): # Gaussian elimination
    N = len(v)
    U = np.zeros((N,N))
    L = np.zeros((N,N))

    for i in range(N):
        U[i,:]=A[i,:]
        
        # Divide by the DIAGONAL element
        div = A[i,i]
        A[i,:] /= div # dividir coluna i por div
        v[i] /= div
        
        # Now subtract from the lower rows
        for j in range(i+1,N): # isto subtrai por colunas e percorre-as na vertical
            mult = A[j ,i]
            A[j,:] -= mult*A[i,:]
            v[j] -= mult*v[i] 
               
    for k in range(N):
        L[:,k] = A[k,:]
    
    # Backsubstitution
    x = np.empty(N,float)
    for i in range(N-1,-1,-1): #vai de N-1 até 0
        x[i] = v[i]
        for j in range(i+1,N):
            x [i] -= A[i, j] * x [j]
            
#     print(L, "= L")
#     print("---")
#     print(U, "= U")
#     print("---")
#     print(L@U, "= LU = A")
    
    return x


A = np.array([[ 4,-1,-1,-1],
              [-1, 3, 0,-1],
              [-1, 0, 3,-1],
              [-1,-1,-1, 4]],float)
v = np.array([5,0,5,0],float)

print(ElimG_LU(A,v))

Resposta = np.linalg.solve(A,v)
print(Resposta)

[3.         1.66666667 3.33333333 2.        ]
[3.         1.66666667 3.33333333 2.        ]
