In [10]:
import numpy as np

def decompQR(A):
    N = len(A[0]) #nº de colunas
    Q = np.copy(A) 
    R = np.zeros((N,N))
     
    u = A[:,0]
    q = u / np.sqrt( np.dot(u,u) )
    Q[:,0] = q
    R[0,0] = np.sqrt( np.dot(u,u) )
    
    for i in range(1,N):
        soma = 0
        for j in range(i):
            soma += np.dot(Q[:,j] , A[:,i]) * Q[:,j]
        
        u = A[:,i] - soma
        R[i,i] = np.sqrt( np.dot(u,u) )
        
        q = u / np.sqrt( np.dot(u,u) )
        Q[:,i] = q
        
    for s in range(N): #precorre as linhas
        t = s + 1
        while t < N: #precorre as colunas dentro de cada linha, a começar na 2ª coluna (t=1)
            R[s,t] = np.dot(Q[:,s] , A[:,t])
            t += 1 
            
    #VERIFICAR - se estiver correto dá igual a A
    #print(Q@R)   
    
    return Q , R

A = np.array([[1, 4, 8, 4],
              [4, 2, 3, 7],
              [8, 3, 6, 9],
              [4, 7, 9, 2]], float)
Q1 , R1 = decompQR(A)
print(Q1,"\n \n", R1)

[[ 0.10153462  0.558463    0.80981107  0.1483773 ]
 [ 0.40613847 -0.10686638 -0.14147555  0.8964462 ]
 [ 0.81227693 -0.38092692  0.22995024 -0.37712564]
 [ 0.40613847  0.72910447 -0.5208777  -0.17928924]] 
 
 [[ 9.8488578   6.49821546 10.55960012 11.37187705]
 [ 0.          5.98106979  8.4234836  -0.484346  ]
 [ 0.          0.          2.74586406  3.27671222]
 [ 0.          0.          0.          3.11592335]]


In [14]:
def valores_proprios(A, erro):
    N = len(A[0]) #nº de colunas  
    
    def decompQR(A):
        Q = np.copy(A) 
        R = np.zeros((N,N))

        u = A[:,0]
        q = u / np.sqrt( np.dot(u,u) )
        Q[:,0] = q
        R[0,0] = np.sqrt( np.dot(u,u) )
        
        for i in range(1,N):
            soma = 0
            for j in range(i):
                soma += np.dot(Q[:,j] , A[:,i]) * Q[:,j]

            u = A[:,i] - soma
            R[i,i] = np.sqrt( np.dot(u,u) )
            q = u / np.sqrt( np.dot(u,u) )
            Q[:,i] = q

        for s in range(N): #precorre as linhas
            t = s + 1
            while t < N: #precorre as colunas dentro de cada linha, a começar na 2ª coluna (t=1)
                R[s,t] = np.dot(Q[:,s] , A[:,t])
                t += 1 

        return Q , R
    
    V = np.identity(N)
   
    while A[0,1] > erro:
        Q,R = decompQR(A)
        A = R @ Q
        V = V @ Q
        
    eignValues = np.diagonal(A) 
    eignVectors = np.diagonal(V) 
        
    return eignValues, eignVectors


M = np.array([[1, 4, 8, 4],
              [4, 2, 3, 7],
              [8, 3, 6, 9],
              [4, 7, 9, 2]], float)

print(valores_proprios(M,10**-6))
# 1, 21, -3, -8    são os valores próprios

(array([21., -8., -3.,  1.]), array([0.43151698, 0.43151698, 0.25819889, 0.25819889]))
