In [31]:
import numpy as np

B = np.array([[0, 3, 1, 0, 8, 6],
              [3, 4, 8, 8, 0, 3],
              [8, 2, 2, 5, 5, 1],
              [0, 3, 9, 1, 7, 2],
              [8, 2, 3, 0, 2, 1],
              [4, 7, 1, 0, 5, 6]],float)

C = np.array([[ 0, 1, 4],
              [ 1,-4, 5],
              [ 2,-2, 3]],float)


def M_inversa(M): # retorna a inversa de uma matriz quadrada
    
    N = len(M[:,0])
    def M_auxiliar(B): # gera a matriz auxiliar de dimensões N x 2N
        #N = len(B[:,0])
        I = np.identity(N)
        B2 = np.zeros((N,2*N))
        for i in range(2*N):
            for j in range(N):
                if i < N:
                    B2[j,i] = B[j,i]
                else:
                    B2[j,i] = I[j,i-N]
        return B2

    def ElimG_Piv_invM(A): # Gaussian elimination com pivotagem para dar a matriz inversa
        #N = len(A[:,0])
        for i in range(N):
            MaiorValor = A[i,i]
            MaiorLinha = i
            # Descobrir qual o Maior valor duma coluna i, e a linha em que ele está
            for k in range(N):
                if MaiorValor < abs(A[k,i]): # uso abs() pq quero livrar-me do 0
                    MaiorValor = A[k,i]
                    MaiorLinha = k

            if MaiorLinha != i: 
                # Trocar a linha antiga pela linha nova em M
                linha_i = np.copy(A[i,:])
                A[i,:] = A[MaiorLinha,:]
                A[MaiorLinha,:] = linha_i

            # Divide by the DIAGONAL element
            div = A[i,i] 
            A[i,:] /= div # dividir coluna i por div

            # Now subtract from the lower rows
            for j in range(i+1,N): # isto subtrai por colunas e percorre-as na vertical
                mult = A[j ,i]
                A[j,:] -= mult*A[i,:]

        for g in range(N-1): # isto subtrai por colunas e percorre-as na vertical
            for h in range(g+1):
                mult2 = A[h,g+1]
                A[h,:] -= mult2*A[g+1,:]

        return A

    def TirarMInv(M): # a matriz M deve ser composta por uma matriz identidade I, e a matriz inversa da original
        #N = len(M[:,0])

        MInv = np.empty((N,N))
        for i in range(N,2*N):
            for j in range(N):
                MInv[j,i-N] = M[j,i]  
        return MInv 
    M1 = M_auxiliar(M)
    M2 = ElimG_Piv_invM(M1)
    Mfinal = TirarMInv(M2)
    
    return Mfinal

B_inv = M_inversa(B)
print(B @ B_inv)

print("----")

C_inv = M_inversa(C)
print(C @ C_inv) # isto deve dar a matriz identidade I

[[ 1.00000000e+00 -1.11022302e-16  1.11022302e-16  1.11022302e-16
  -2.22044605e-16  1.80411242e-16]
 [-2.77555756e-16  1.00000000e+00  0.00000000e+00  5.55111512e-17
   0.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.11022302e-16  1.00000000e+00 -5.55111512e-17
   2.22044605e-16  5.55111512e-17]
 [ 2.77555756e-17 -2.77555756e-17 -6.93889390e-17  1.00000000e+00
  -5.55111512e-17  0.00000000e+00]
 [ 1.11022302e-16  2.77555756e-17 -1.38777878e-16 -8.32667268e-17
   1.00000000e+00  5.55111512e-17]
 [-3.88578059e-16 -2.77555756e-17  5.55111512e-17 -5.55111512e-17
   1.11022302e-16  1.00000000e+00]]
----
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  8.32667268e-17]
 [ 5.55111512e-17 -5.55111512e-17  1.00000000e+00]]


Fazer a  eliminaçao de gauss outra vez so que agora a começar dde baixo para cima
